### ISSUE TITLE
uninitialized constant CGRect (NameError) when building for OSX

### ISSUE THREAD

**Issue by donokuda** [colinta/teacup#85]
I get a NameError when trying to use teacup in OSX.

With the simple-osx sample app:
When I run `rake` I get the following output

```
2013-05-26 23:10:04.944 teacup-osx[96600:707] Could not connect the action buttonPressed: to target of class NSApplication
2013-05-26 21:43:39.501 teacup-osx[15048:707] handler.rb:60:in `block in apply:': uninitialized constant CGRect (NameError)
        from handler.rb:54:in `apply:'
        from handler.rb:35:in `block in apply_hash:'
        from handler.rb:34:in `apply_hash:'
        from layout.rb:158:in `layout:'
        from layout.rb:231:in `subview:'
        from layout.rb:171:in `layout:'
        from teacup_controller.rb:101:in `teacupDidLoad'
        from ns_view_controller.rb:14:in `loadView'
        from layout.rb:171:in `layout:'
        from teacup_controller.rb:101:in `teacupDidLoad'
        from ns_window_controller.rb:6:in `windowDidLoad'
        from app_delegate.rb:10:in `buildWindow'
        from app_delegate.rb:5:in `applicationDidFinishLaunching:'
```

**Comment by colinta** [comment]
Shoot, thanks, should be an easy fix.

**Comment by donokuda** [comment]
Thanks! Let me know if there's anything I can do to help

**Comment by colinta** [comment]
Pushed 2.0.3, which should have fixed this.  Let me know! :-D

**Comment by donokuda** [comment]
:100: Works! Thanks, @colinta!
